// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciDersYonetim.Data.Context;

#nullable disable

namespace OgrenciDersYonetim.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422223242_IlkMigration")]
    partial class IlkMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DersKodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kredi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ogretmen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dersler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Temel matematik dersi",
                            DersAdi = "Matematik",
                            DersKodu = "MAT101",
                            EklenmeTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kredi = 4,
                            Ogretmen = "Prof. Dr. Ali Veli"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Temel fizik dersi",
                            DersAdi = "Fizik",
                            DersKodu = "FIZ101",
                            EklenmeTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kredi = 3,
                            Ogretmen = "Doç. Dr. Ayşe Kaya"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Programlamaya giriş",
                            DersAdi = "Bilgisayar Bilimi",
                            DersKodu = "BIL101",
                            EklenmeTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kredi = 3,
                            Ogretmen = "Dr. Mehmet Can"
                        });
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Sistem",
                            Email = "admin@okul.edu.tr",
                            KayitTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "admin",
                            Rol = "Admin",
                            SifreHash = "ea8c6f6a71f8fef5e4e96765bfd2c3f0e7bdf6e8c0d9e8f8a1b2c3d4e5f6a7b8",
                            Soyad = "Yöneticisi"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ahmet",
                            Email = "ogretmen1@okul.edu.tr",
                            KayitTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "ogretmen1",
                            Rol = "Ogretmen",
                            SifreHash = "ea8c6f6a71f8fef5e4e96765bfd2c3f0e7bdf6e8c0d9e8f8a1b2c3d4e5f6a7b8",
                            Soyad = "Yılmaz"
                        });
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OgrenciNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.HasIndex("OgrenciNo")
                        .IsUnique();

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.OgrenciDers", b =>
                {
                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DersId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtamaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Not")
                        .HasColumnType("REAL");

                    b.HasKey("OgrenciId", "DersId");

                    b.HasIndex("DersId");

                    b.ToTable("OgrenciDersler");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Ogrenci", b =>
                {
                    b.HasOne("OgrenciDersYonetim.Core.Entities.Kullanici", "Kullanici")
                        .WithOne("OgrenciProfil")
                        .HasForeignKey("OgrenciDersYonetim.Core.Entities.Ogrenci", "KullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.OgrenciDers", b =>
                {
                    b.HasOne("OgrenciDersYonetim.Core.Entities.Ders", "Ders")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciDersYonetim.Core.Entities.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Ders", b =>
                {
                    b.Navigation("OgrenciDersler");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("OgrenciProfil");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Ogrenci", b =>
                {
                    b.Navigation("OgrenciDersler");
                });
#pragma warning restore 612, 618
        }
    }
}
