// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciDersYonetim.Data.Context;

#nullable disable

namespace OgrenciDersYonetim.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501213653_DersIcerikEkle")]
    partial class DersIcerikEkle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DersKodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kredi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ogretmen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dersler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Temel matematik dersi",
                            DersAdi = "Matematik",
                            DersKodu = "MAT101",
                            EklenmeTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kredi = 4,
                            Ogretmen = "Prof. Dr. Ali Veli"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Temel fizik dersi",
                            DersAdi = "Fizik",
                            DersKodu = "FIZ101",
                            EklenmeTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kredi = 3,
                            Ogretmen = "Doç. Dr. Ayşe Kaya"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Programlamaya giriş",
                            DersAdi = "Bilgisayar Bilimi",
                            DersKodu = "BIL101",
                            EklenmeTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kredi = 3,
                            Ogretmen = "Dr. Mehmet Can"
                        });
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.DersIcerik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DersId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EkleyenKullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonTeslimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.ToTable("DersIcerikler");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Devamsizlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DersId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GirenKullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("Devamsizliklar");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Sistem",
                            Email = "admin@okul.edu.tr",
                            KayitTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "admin",
                            Rol = "Admin",
                            SifreHash = "3eb3fe66b31e3b4d10fa70b5cad49c7112294af6ae4e476a1c405155d45aa121",
                            Soyad = "Yoneticisi"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ahmet",
                            Email = "ogretmen1@okul.edu.tr",
                            KayitTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "ogretmen1",
                            Rol = "Ogretmen",
                            SifreHash = "3eb3fe66b31e3b4d10fa70b5cad49c7112294af6ae4e476a1c405155d45aa121",
                            Soyad = "Yilmaz"
                        });
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Not", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DersId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GirenKullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NotDegeri")
                        .HasColumnType("REAL");

                    b.Property<string>("NotTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("Notlar");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OgrenciNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.HasIndex("OgrenciNo")
                        .IsUnique();

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.OgrenciDers", b =>
                {
                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DersId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtamaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Not")
                        .HasColumnType("REAL");

                    b.HasKey("OgrenciId", "DersId");

                    b.HasIndex("DersId");

                    b.ToTable("OgrenciDersler");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Ogretmen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brans")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Ogretmenler");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.OgretmenDers", b =>
                {
                    b.Property<int>("OgretmenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DersId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtamaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("OgretmenId", "DersId");

                    b.HasIndex("DersId");

                    b.ToTable("OgretmenDersler");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.DersIcerik", b =>
                {
                    b.HasOne("OgrenciDersYonetim.Core.Entities.Ders", "Ders")
                        .WithMany("DersIcerikler")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Devamsizlik", b =>
                {
                    b.HasOne("OgrenciDersYonetim.Core.Entities.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciDersYonetim.Core.Entities.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Not", b =>
                {
                    b.HasOne("OgrenciDersYonetim.Core.Entities.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciDersYonetim.Core.Entities.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Ogrenci", b =>
                {
                    b.HasOne("OgrenciDersYonetim.Core.Entities.Kullanici", "Kullanici")
                        .WithOne("OgrenciProfil")
                        .HasForeignKey("OgrenciDersYonetim.Core.Entities.Ogrenci", "KullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.OgrenciDers", b =>
                {
                    b.HasOne("OgrenciDersYonetim.Core.Entities.Ders", "Ders")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciDersYonetim.Core.Entities.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Ogretmen", b =>
                {
                    b.HasOne("OgrenciDersYonetim.Core.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.OgretmenDers", b =>
                {
                    b.HasOne("OgrenciDersYonetim.Core.Entities.Ders", "Ders")
                        .WithMany("OgretmenDersler")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciDersYonetim.Core.Entities.Ogretmen", "Ogretmen")
                        .WithMany("OgretmenDersler")
                        .HasForeignKey("OgretmenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogretmen");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Ders", b =>
                {
                    b.Navigation("DersIcerikler");

                    b.Navigation("OgrenciDersler");

                    b.Navigation("OgretmenDersler");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("OgrenciProfil");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Ogrenci", b =>
                {
                    b.Navigation("OgrenciDersler");
                });

            modelBuilder.Entity("OgrenciDersYonetim.Core.Entities.Ogretmen", b =>
                {
                    b.Navigation("OgretmenDersler");
                });
#pragma warning restore 612, 618
        }
    }
}
